export const DETAILS_REQUEST = 'DETAILS_REQUEST';
export const DETAILS_SUCCESS = 'DETAILS_SUCCESS';
export const DETAILS_FAILURE = 'DETAILS_FAILURE';

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";